# Generated by Django 4.2.13 on 2024-06-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='formatted_address',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
